spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime_teste_db?useTimezone=true&serverTimezone=America/Sao_Paulo&CreateDatabaseIfNotExists=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false